name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      # Optional: show directory layout for debugging
      - name: Show layout
        run: |
          pwd
          ls -la
          echo "--- docs ---"
          ls -la docs || true

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      # If gh-pages branch is missing, initialize it once using --skip-build
      - name: Ensure gh-pages branch exists (init if missing)
        working-directory: docs
        env:
          GIT_USER: github-actions[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git ls-remote --exit-code --heads origin gh-pages >/dev/null 2>&1; then
            echo "GH_PAGES_EXISTS=true" >> $GITHUB_ENV
            echo "gh-pages branch exists."
          else
            echo "GH_PAGES_EXISTS=false" >> $GITHUB_ENV
            echo "gh-pages branch not found. Initializing with --skip-build..."
            npm run deploy -- --skip-build
          fi

      - name: Build
        working-directory: docs
        run: npm run build

      - name: Deploy to gh-pages
        working-directory: docs
        env:
          GIT_USER: github-actions[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # If we just created gh-pages above, now push the real build
          npm run deploy
